module.exports = {
    AUTHENTICATION_ERROR : 9001,
    AUTHENTICATION_ERROR_NOUSER : 9002,
    AUTHENTICATION_ERROR_WRONGPASS : 9003,
    AUTHENTICATION_ERROR_NOACCESS : 9004,
    REQUEST_FORMAT_ERROR : 9101,
    INTERNAL_SERVER_ERROR : 9201
};